server:
  port: 8095

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/rahul-java/microservice-configuration
          clone-on-start: true
     